services:
  app:
    image: backend:latest
    ports:
      - "80:80"
    environment:
      - SERVER_ADDRESS=REDACTED
      - SERVER_PORT=80
      - DB_USER=backenduser
      - DB_PASSWORD=superStrongPassword
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=db
      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=my-bucket
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
  bot:
    image: bot:latest
    depends_on:
      - app
  postgres:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=backenduser
      - POSTGRES_PASSWORD=superStrongPassword
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backenduser -d db"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.1
    restart: on-failure:3
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=postgres user=backenduser password=superStrongPassword dbname=db sslmode=disable
    volumes:
      - ./migrations:/migrations/
    depends_on:
      postgres:
        condition: service_healthy
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000" # API MinIO
      - "9001:9001" # Web-интерфейс MinIO
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:
