// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clients/auth/sign-in": {
            "post": {
                "description": "sign-in in client with given data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clients"
                ],
                "summary": "Sign-in for client",
                "parameters": [
                    {
                        "description": "Credentials to use",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.signInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.clientSignResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/clients/auth/sign-up": {
            "post": {
                "description": "create client with given data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clients"
                ],
                "summary": "Create client",
                "parameters": [
                    {
                        "description": "Credentials to use",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Client"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.clientSignResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/moderation": {
            "get": {
                "description": "Get list for moderation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Moderation"
                ],
                "summary": "Get not approved endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    },
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            },
            "post": {
                "description": "Change moderation status for promo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Moderation"
                ],
                "summary": "Moderate promo",
                "parameters": [
                    {
                        "description": "Verdict of moderator",
                        "name": "Verdict",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ModerationBody"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/partners": {
            "get": {
                "description": "Returning list of partners for client",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Partners"
                ],
                "summary": "Partners endpoint",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Partner"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/partners/auth/sign-in": {
            "post": {
                "description": "sign-in in partners with given data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Partners"
                ],
                "summary": "Sign-in for partners",
                "parameters": [
                    {
                        "description": "Credentials to use",
                        "name": "partner",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.signInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.partnerSignResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/partners/auth/sign-up": {
            "post": {
                "description": "sign-up partner with given data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Partners"
                ],
                "summary": "Sign-up partner",
                "parameters": [
                    {
                        "description": "Credentials to use",
                        "name": "partner",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Partner"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.partnerSignResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/partners/{partnerID}/promos": {
            "get": {
                "description": "Returning list of promos of specific partner for client",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PromosForClient"
                ],
                "summary": "Promo endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Partner ID",
                        "name": "partnerID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Promo"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/partners/{partnerID}/promos/{promoID}": {
            "get": {
                "description": "Returning promo for client",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PromosForClient"
                ],
                "summary": "Promo endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Partner ID",
                        "name": "partnerID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Partner ID",
                        "name": "promoID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/partners/{partnerID}/promos/{promoID}/img": {
            "get": {
                "description": "Returns the image associated with a specific promo",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "PromosForClient"
                ],
                "summary": "Get promo image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Partner ID",
                        "name": "partnerID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Promo ID",
                        "name": "promoID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image file data",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "error: Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error: Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "error: Изображение не найдено",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/partners/{partnerID}/stat": {
            "get": {
                "description": "Возвращает метрики использования промо-кодов, такие как активные пользователи, количество покупок, retention и т. д.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistics"
                ],
                "summary": "Получение статистики по промо-акциям",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID партнера",
                        "name": "partnerID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ со статистикой",
                        "schema": {
                            "$ref": "#/definitions/models.Stat"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных. Пример: {\\\"error\\\": \\\"Некорректный\tUUID\tпартнера\\\"}",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации. Пример: {\\\"error\\\": \\\"Некорректный\t\t\tтокен\tили\t\t\tпользователь\tне\tаутентифицирован\\\"}",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Ошибка доступа. Пример: {\\\"error\\\": \\\"Недостаточно\t\t\t\tправ\tдля\t\t\tпросмотра\t\tстатистики\\\"}",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера. Пример: {\\\"error\\\": \\\"Ошибка\t\tпри\t\tполучении\tстатистики\\\"}",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/partners/{partnerID}/stat/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Генерирует Excel-файл с активациями промокодов партнера",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "Statistics"
                ],
                "summary": "Экспорт статистики партнера",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID партнера",
                        "name": "partnerID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Некорректный UUID",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/partners/{partnerID}/stat/{promoID}": {
            "get": {
                "description": "Stats for partner for specific promo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Stats endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Partner ID",
                        "name": "partnerID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Promo ID",
                        "name": "promoID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StatPromo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Returns a pong response to indicate the service is up and running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Ping endpoint",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/promos": {
            "get": {
                "description": "Get promo by partner",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PromosForPartners"
                ],
                "summary": "Promo endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Promo"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            },
            "post": {
                "description": "Create promo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PromosForPartners"
                ],
                "summary": "Promo endpoint",
                "parameters": [
                    {
                        "description": "Promo",
                        "name": "promo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/promos/activate": {
            "post": {
                "description": "Activate promo for client",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PromosForPartners"
                ],
                "summary": "Promo endpoint",
                "parameters": [
                    {
                        "description": "Activation Request",
                        "name": "promo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ActivationRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/promos/{promoID}": {
            "get": {
                "description": "Get promo by partner",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PromosForPartners"
                ],
                "summary": "Promo endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Promo ID",
                        "name": "promoID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete promo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PromosForPartners"
                ],
                "summary": "Promo endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Promo ID",
                        "name": "promoID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        },
        "/promos/{promoID}/img/upload": {
            "post": {
                "description": "Allows partners to upload an image for a specific promo",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PromosForPartners"
                ],
                "summary": "Upload promo image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Promo ID",
                        "name": "promoID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Файл успешно загружен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error: Файл обязателен",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error: Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error: Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/promos/{promoID}/{clientID}": {
            "get": {
                "description": "Get promo by partner",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PromosForPartners"
                ],
                "summary": "Promo endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Promo ID",
                        "name": "promoID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client ID",
                        "name": "clientID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization header must be set for access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PromoCLientView"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.Err"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.clientSignResponse": {
            "type": "object",
            "required": [
                "name",
                "phone_number"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "handlers.partnerSignResponse": {
            "type": "object",
            "required": [
                "description",
                "image_id",
                "phone_number",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 3
                },
                "id": {
                    "type": "string"
                },
                "image_id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "handlers.signInRequest": {
            "type": "object",
            "required": [
                "password",
                "phone_number"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "models.ActivationRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "promo_id": {
                    "type": "string"
                }
            }
        },
        "models.Client": {
            "type": "object",
            "required": [
                "name",
                "phone_number"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "models.Condition": {
            "type": "object",
            "properties": {
                "buy": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "COMMON",
                        "UNIQUE",
                        "BUNDLE"
                    ]
                }
            }
        },
        "models.ErrorResponse": {
            "description": "Структура ошибки, возвращаемая API в формате { \"error\": \"message\" }",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Сообщение об ошибке"
                }
            }
        },
        "models.ModerationBody": {
            "type": "object",
            "properties": {
                "partner_id": {
                    "type": "string"
                },
                "promo_id": {
                    "type": "string"
                },
                "verdict": {
                    "type": "boolean"
                }
            }
        },
        "models.Partner": {
            "type": "object",
            "required": [
                "description",
                "image_id",
                "phone_number",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 3
                },
                "id": {
                    "type": "string"
                },
                "image_id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "models.Promo": {
            "type": "object",
            "required": [
                "condition",
                "image_id"
            ],
            "properties": {
                "condition": {
                    "$ref": "#/definitions/models.Condition"
                },
                "condition_string": {
                    "description": "✅ ИСПРАВЛЕНО ЗДЕСЬ!",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image_id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_approved": {
                    "type": "boolean"
                },
                "partner_id": {
                    "type": "string"
                },
                "promo_id": {
                    "type": "string"
                },
                "time_limit_end": {
                    "type": "integer"
                },
                "time_limit_start": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "usage_limit": {
                    "type": "integer"
                }
            }
        },
        "models.PromoCLientView": {
            "type": "object",
            "required": [
                "condition",
                "image_id"
            ],
            "properties": {
                "buy": {
                    "type": "integer"
                },
                "condition": {
                    "$ref": "#/definitions/models.Condition"
                },
                "condition_string": {
                    "description": "✅ ИСПРАВЛЕНО ЗДЕСЬ!",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "image_id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_approved": {
                    "type": "boolean"
                },
                "overall": {
                    "type": "integer"
                },
                "partner_id": {
                    "type": "string"
                },
                "promo_id": {
                    "type": "string"
                },
                "time_limit_end": {
                    "type": "integer"
                },
                "time_limit_start": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "usage_limit": {
                    "type": "integer"
                }
            }
        },
        "models.Stat": {
            "description": "Структура, содержащая основные бизнес-метрики использования промо-кодов.",
            "type": "object",
            "properties": {
                "active_promos_count": {
                    "description": "Количество активных промо-акций, которые в данный момент доступны клиентам.\nПромо-акция считается активной, если у нее ` + "`" + `is_active = true` + "`" + `.",
                    "type": "integer",
                    "example": 5
                },
                "active_users_count": {
                    "description": "Количество уникальных пользователей, которые использовали промо-коды.\nКаждый клиент считается только один раз, независимо от количества активаций.",
                    "type": "integer",
                    "example": 85
                },
                "buy_promos_count": {
                    "description": "Общее количество покупок, совершенных с использованием промо-кодов.\nСчитается суммарное количество активаций промо, приведших к покупке.",
                    "type": "integer",
                    "example": 120
                },
                "conversion_rate": {
                    "description": "Конверсия пользователей в использование промо-кодов (в процентах).\nРассчитывается как ` + "`" + `(ActiveUsers / TotalClients) * 100` + "`" + `.",
                    "type": "number",
                    "example": 17
                },
                "daily_active_users_count": {
                    "description": "Количество уникальных пользователей, активировавших промо-коды за последние 24 часа.\nПоказывает ежедневную вовлеченность клиентов в акции.",
                    "type": "integer",
                    "example": 25
                },
                "daily_buy_promo_count": {
                    "description": "Количество покупок, совершенных с промо-кодами за последние 24 часа.\nПолезно для оценки текущей активности пользователей.",
                    "type": "integer",
                    "example": 30
                },
                "limit_promos_count": {
                    "description": "Количество промо-акций, достигших лимита использования.\nНапример, если промо-код имеет ограничение ` + "`" + `usage_limit = 100` + "`" + `, то он больше не учитывается после достижения лимита.",
                    "type": "integer",
                    "example": 10
                },
                "retention_30d": {
                    "description": "Количество клиентов, которые использовали промо-коды повторно в последние 30 дней.\nЭтот показатель помогает измерить уровень удержания клиентов.",
                    "type": "integer",
                    "example": 40
                },
                "top_users": {
                    "description": "Количество топ-клиентов, которые использовали промо-коды чаще всего.\nЭтот показатель можно использовать для определения лояльных клиентов.",
                    "type": "integer",
                    "example": 10
                },
                "total_users": {
                    "description": "Общее количество зарегистрированных клиентов у партнера.\nПолезно для оценки охвата бизнеса и анализа конверсии в использование промо-кодов.",
                    "type": "integer",
                    "example": 500
                }
            }
        },
        "models.StatPromo": {
            "type": "object",
            "properties": {
                "buy_promos_count": {
                    "type": "integer"
                },
                "daily_buy_promo_count": {
                    "type": "integer"
                },
                "daily_users_count": {
                    "type": "integer"
                },
                "users_count": {
                    "type": "integer"
                }
            }
        },
        "utils.Err": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "prod-team-29-4254c2ee.REDACTED",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Crazy Peppers T-Loyal API",
	Description:      "T-Loyal API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
